version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
    command: "--http_port 8222 --js"  # Enable JetStream
    volumes:
      - nats-data:/data
    restart: unless-stopped

volumes:
  nats-data: